### ISSUE TITLE
Base size not changing

### ISSUE THREAD

**Issue by sussweb** [craigrileyuk/tailwind-fluid-typography#1]
The remSize setting doesn't seem to have any effect. No matter what value I set here, the class fluid-base always sticks to 16px. 
I would prefer a bigger base-font size.

**Comment by vanling** [comment]
I was expecting the fluid-base to change too 👍

**Comment by craigrileyuk** [comment]
I've added a clearer explanation of this prop to the README. Thanks for the feedback.

Base font is just what you declare in your `<html>` tag:

```css
html {
    font-size: 18px;
}
```

**Comment by topada** [comment]
I would expect the **base font size**  to grow and shrink within limits.
